INSERT INTO contenido (
  contenido_id,
  nombre_visible,
  categoria,
  subcategoria,
  ubicacion,
  tipo_campo,
  cantidad_sugerida,
  cantidad_minima,
  estado,
  opcionales,
  detalle_largo,
  imagen
) VALUES
(254729, 'Venda israelí', 'Control de Sangrados y Curaciones', 'Descartable', 'Botiquín de control de sangrados', 'Numérico', 2, 1, 'Disponible', '{}'::jsonb, '', ''),
(287438, 'Tegaderm', 'Otros', 'Descartable', 'Compartimento Central del Botiquín', 'Numérico', 6, 1, 'Disponible', '{}'::jsonb, '', ''),
(294428, 'Ventilador Manual Pediátrico', 'Oxigenoterapia', 'Equipo', '10 Compartimento Mueble', 'NoDefinido', 2, 0, 'Disponible', '{}'::jsonb, '', ''),
(313079, 'Carbón activado', 'Medicamentos de emergencia', 'Antídoto', 'Caja de medicamentos', 'NoDefinido', 1, 0, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Valor":"01/01/24","Tipo":"fecha"}}'::jsonb, '', ''),
(184716, 'Juego de cánulas orofaríngeas 6 tamaños', 'Oxigenoterapia', 'Descartable', 'Bolso Azul Vía Aérea Ferno', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, 'Usado para aliviar la inflamación y el dolor moderado.', 'url_a_imagen_placeholder_2'),
(169615, 'Termómetro digital', 'Equipo de Signos Vitales', 'Equipo', 'Bolso Signos Vitales', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(256366, 'Mango laringoscopio con baterías', 'Equipo de intubación', 'Equipo', 'Bolso Azul Vía Aérea Ferno', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(265988, 'Captopril 25mg', 'Medicamentos de emergencia', 'Antihipertensivo', 'Caja de medicamentos', 'NoDefinido', 0, 0, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Valor":"30/12/2024","Tipo":"text"}}'::jsonb, '', ''),
(118532, 'Guantes quirúrgicos individuales talla 6,7,8', 'EPP y Ropa descartable Ambulancia', 'Descartable', '9 Compartimento Mueble', 'NoDefinido', 4, 0, 'Disponible', '{}'::jsonb, '', ''),
(123951, 'Rocuronio 50mg/5ml', 'Medicamentos del botiquín', 'Paralizante', 'Caja de medicamentos', 'Numérico', 2, 1, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Tipo":"fecha","Valor":"30/12/2024"}}'::jsonb, '', ''),
(292405, 'Bicarbonato de sodio 8,4% p/v', 'Medicamentos de emergencia', 'Antiácidos', 'Caja de medicamentos', 'Numérico', 6, 1, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Tipo":"fecha","Valor":"30/12/2024"}}'::jsonb, '', ''),
(256443, 'Catéter Intravenoso', 'Terapia IV / IM', 'Descartable', 'Compartimento A del botiquín', 'NoDefinido', 3, 0, 'Disponible', '{
  "Opcion1":{"Nombre":"Catéter #24","Valor":"6","Tipo":"text"},
  "Opcion2":{"Nombre":"Catéter #22","Valor":"6","Tipo":"text"},
  "Opcion3":{"Nombre":"Catéter #20","Valor":"6","Tipo":"text"},
  "Opcion4":{"Nombre":"Catéter #18","Valor":"6","Tipo":"text"},
  "Opcion5":{"Nombre":"Catéter #16","Valor":"6","Tipo":"text"},
  "Opcion6":{"Nombre":"Catéter #14","Valor":"6","Tipo":"text"}
}'::jsonb, '6 de cada uno', ''),
(216664, 'Sensor de capnógrafo', 'Otros', 'Descartable', 'Bolso Monitor Cardiaco', 'NoDefinido', 3, 0, 'Disponible', '{}'::jsonb, '', ''),
(291194, 'Aspirador portátil', 'Oxigenoterapia', 'Equipo', '1 Compartimento mueble', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, 'Medicamento usado para aliviar el dolor y la fiebre.', 'url_a_imagen_placeholder_1'),
(123523, 'Adenosina 6mg/2ml', 'Medicamentos de emergencia', 'Antiarrítmicos', 'Caja de medicamentos', 'Numérico', 3, 1, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Tipo":"fecha","Valor":"30/12/2024"}}'::jsonb, '', ''),
(227672, 'Aguja 25G', 'Terapia IV / IM', 'Descartable', '5 Compartimento Mueble', 'NoDefinido', 6, 0, 'Disponible', '{}'::jsonb, '', ''),
(251042, 'Torniquete de unión SAM', 'Control de Sangrados y Curaciones', 'Equipo', '14 Compartimento Mueble', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(233198, 'Férula Espalda Ped. c/ Sujetador', 'Equipo de Inmovilización', 'Equipo', '15 Compartimento Mueble', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(311198, 'Parche Marcapasos', 'Otros', 'Descartable', '9 Compartimento Mueble', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(304065, 'Férulas al vacío 3 uds', 'Equipo de Inmovilización', 'Equipo', '15 Compartimento Mueble', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(115116, 'Torniquete SAM', 'Control de Sangrados y Curaciones', 'Descartable', 'Botiquín de control de sangrados', 'Numérico', 2, 1, 'Disponible', '{}'::jsonb, '', ''),
(274809, 'Jeringas 1 ml', 'Terapia IV / IM', 'Descartable', '5 Compartimento Mueble', 'NoDefinido', 6, 0, 'Disponible', '{}'::jsonb, '', ''),
(183394, 'Diclofenaco 75mg/3ml', 'Medicamentos del botiquín', 'Analgésicos', 'Caja de medicamentos', 'Numérico', 6, 1, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Tipo":"fecha","Valor":"30/12/2024"}}'::jsonb, '', ''),
(223193, 'Tijera de trabajo pesado', 'Equipo de Signos Vitales', 'Equipo', 'Compartimento Central del Botiquín', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(194471, 'Apósitos 4x4 Estériles', 'Control de Sangrados y Curaciones', 'Descartable', 'Botiquín de control de sangrados', 'Numérico', 6, 1, 'Disponible', '{}'::jsonb, '', ''),
(176487, 'Jeringa 3 ml', 'Terapia IV / IM', 'Descartable', 'Compartimento A del botiquín', 'Numérico', 6, 1, 'Disponible', '{}'::jsonb, '', ''),
(208673, 'Bolsa Roja', 'Otros', 'Descartable', 'Compartimento Central del Botiquín', 'Numérico', 3, 1, 'Disponible', '{}'::jsonb, '', ''),
(291180, 'Dexametasona 4mg/ml', 'Medicamentos del botiquín', 'Esteroide', 'Caja de medicamentos', 'Numérico', 6, 1, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Tipo":"fecha","Valor":"01/01/24"}}'::jsonb, '', ''),
(130554, 'Suero fisiológico 100 ml', 'Terapia IV / IM', 'Descartable', '3 Compartimento Mueble', 'NoDefinido', 6, 0, 'Disponible', '{}'::jsonb, '', ''),
(190978, 'Metoclopramida 10mg/2ml', 'Medicamentos del botiquín', 'Procinéticos', 'Caja de medicamentos', 'Numérico', 3, 1, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Tipo":"fecha","Valor":"30/12/2024"}}'::jsonb, '', ''),
(218896, 'Sistema fijo de Oxígeno Cilindro', 'Oxigenoterapia', 'Equipo', 'Modulo De Ambulancia', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(109085, 'Jeringas 5 ml', 'Terapia IV / IM', 'Descartable', '5 Compartimento Mueble', 'NoDefinido', 12, 0, 'Disponible', '{}'::jsonb, '', ''),
(111445, 'Aguja intraósea 25 mm', 'Terapia IV / IM', 'Descartable', 'Compartimento Central del Botiquín', 'Numérico', 1, 1, 'Disponible', '{}'::jsonb, '', ''),
(137947, 'Jeringas 10 ml', 'Terapia IV / IM', 'Descartable', '5 Compartimento Mueble', 'NoDefinido', 6, 0, 'Disponible', '{}'::jsonb, '', ''),
(178069, 'Guantes de alto riesgo talla M', 'EPP y Ropa descartable Ambulancia', 'Descartable', '7 compartimento Mueble', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(356366, 'Mango laringoscopio con baterías', 'Equipo de intubación', 'Equipo', 'Bolso Azul Vía Aérea Ferno', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(265981, 'Captopril 25mg', 'Medicamentos de emergencia', 'Antihipertensivo', 'Caja de medicamentos', 'NoDefinido', 0, 0, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Valor":"30/12/2024","Tipo":"text"}}'::jsonb, '', ''),
(118531, 'Guantes quirúrgicos individuales talla 6,7,8', 'EPP y Ropa descartable Ambulancia', 'Descartable', '9 Compartimento Mueble', 'NoDefinido', 4, 0, 'Disponible', '{}'::jsonb, '', ''),
(148716, 'Guantes de alto riesgo talla L', 'EPP y Ropa descartable Ambulancia', 'Descartable', '7 compartimento Mueble', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(267388, 'Salbutamol 100mcg inhalador', 'Medicamentos del botiquín', 'Broncodilatador', 'Caja de medicamentos', 'Numérico', 2, 1, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Valor":"01/01/24","Tipo":"fecha"}}'::jsonb, '', ''),
(176374, 'Gluconato de calcio 10%', 'Medicamentos del botiquín', 'Electrolito', 'Caja de medicamentos', 'Numérico', 1, 1, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Valor":"01/01/24","Tipo":"fecha"}}'::jsonb, '', ''),
(278316, 'Guantes de nitrilo talla M', 'EPP y Ropa descartable Ambulancia', 'Descartable', '7 compartimento Mueble', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(224353, 'Guantes de nitrilo talla L', 'EPP y Ropa descartable Ambulancia', 'Descartable', '7 compartimento Mueble', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(294842, 'Adrenalina 1mg/1ml', 'Medicamentos de emergencia', 'Vasopresor', 'Caja de medicamentos', 'Numérico', 4, 1, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Valor":"30/12/2024","Tipo":"fecha"}}'::jsonb, '', ''),
(291184, 'Metilprednisolona 125mg', 'Medicamentos de emergencia', 'Esteroide', 'Caja de medicamentos', 'Numérico', 1, 1, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Valor":"01/01/24","Tipo":"fecha"}}'::jsonb, '', ''),
(130839, 'Furosemida 20mg/2ml', 'Medicamentos del botiquín', 'Diurético', 'Caja de medicamentos', 'Numérico', 1, 1, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Valor":"01/01/24","Tipo":"fecha"}}'::jsonb, '', ''),
(214136, 'Cánula Nasal Adulto', 'Oxigenoterapia', 'Descartable', 'Bolso Azul Vía Aérea Ferno', 'NoDefinido', 2, 0, 'Disponible', '{}'::jsonb, '', ''),
(293558, 'Cánula Nasal Pediátrico', 'Oxigenoterapia', 'Descartable', 'Bolso Azul Vía Aérea Ferno', 'NoDefinido', 2, 0, 'Disponible', '{}'::jsonb, '', ''),
(257049, 'Máscara Venturi', 'Oxigenoterapia', 'Descartable', 'Bolso Azul Vía Aérea Ferno', 'NoDefinido', 2, 0, 'Disponible', '{}'::jsonb, '', ''),
(130870, 'Máscara No Reinalación Adulto', 'Oxigenoterapia', 'Descartable', 'Bolso Azul Vía Aérea Ferno', 'NoDefinido', 2, 0, 'Disponible', '{}'::jsonb, '', ''),
(222361, 'Máscara No Reinalación Pediátrico', 'Oxigenoterapia', 'Descartable', 'Bolso Azul Vía Aérea Ferno', 'NoDefinido', 2, 0, 'Disponible', '{}'::jsonb, '', ''),
(291182, 'Atropina 1mg/1ml', 'Medicamentos de emergencia', 'Anticolinérgico', 'Caja de medicamentos', 'Numérico', 2, 1, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Valor":"01/01/24","Tipo":"fecha"}}'::jsonb, '', ''),
(264163, 'Nitroglicerina Spray Sublingual', 'Medicamentos de emergencia', 'Antianginoso', 'Caja de medicamentos', 'Numérico', 1, 1, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Valor":"01/01/24","Tipo":"fecha"}}'::jsonb, '', ''),
(173179, 'Ondansetrón 4mg/2ml', 'Medicamentos del botiquín', 'Antiemético', 'Caja de medicamentos', 'Numérico', 2, 1, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Valor":"01/01/24","Tipo":"fecha"}}'::jsonb, '', ''),
(201528, 'Paracetamol 500mg', 'Medicamentos del botiquín', 'Analgésico', 'Caja de medicamentos', 'Numérico', 20, 5, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Valor":"01/01/24","Tipo":"fecha"}}'::jsonb, '', ''),
(114838, 'Cloruro de sodio 0.9%', 'Terapia IV / IM', 'Descartable', '3 Compartimento Mueble', 'NoDefinido', 6, 0, 'Disponible', '{}'::jsonb, '', ''),
(289381, 'Adrenalina 1mg/10ml', 'Medicamentos de emergencia', 'Vasopresor', 'Caja de medicamentos', 'Numérico', 2, 1, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Valor":"30/12/2024","Tipo":"fecha"}}'::jsonb, '', ''),
(169616, 'Termómetro digital', 'Equipo de Signos Vitales', 'Equipo', 'Bolso Signos Vitales', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(274789, 'Amiodarona 150mg/3ml', 'Medicamentos de emergencia', 'Antiarrítmicos', 'Caja de medicamentos', 'Numérico', 3, 1, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Valor":"30/12/2024","Tipo":"fecha"}}'::jsonb, '', ''),
(156899, 'Lidocaína 2% 50ml', 'Medicamentos del botiquín', 'Anestésico', 'Caja de medicamentos', 'Numérico', 2, 1, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Valor":"30/12/2024","Tipo":"fecha"}}'::jsonb, '', ''),
(143118, 'Succionador manual', 'Oxigenoterapia', 'Equipo', 'Bolso Azul Vía Aérea Ferno', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(120314, 'Epinefrina 1:1000', 'Medicamentos de emergencia', 'Vasopresor', 'Caja de medicamentos', 'Numérico', 2, 1, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Valor":"01/01/24","Tipo":"fecha"}}'::jsonb, '', ''),
(123456, 'Amoxicilina 500mg', 'Medicamentos del botiquín', 'Antibiótico', 'Caja de medicamentos', 'Numérico', 10, 2, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Valor":"01/01/24","Tipo":"fecha"}}'::jsonb, '', ''),
(299384, 'Ketorolaco 30mg/1ml', 'Medicamentos del botiquín', 'Analgésico', 'Caja de medicamentos', 'Numérico', 6, 1, 'Disponible', '{"Opcion1":{"Nombre":"Fecha Vencimiento","Valor":"30/12/2024","Tipo":"fecha"}}'::jsonb, '', ''),
(156789, 'Desfibrilador externo automático (DEA)', 'Equipo de Signos Vitales', 'Equipo', 'Modulo de Ambulancia', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(190581, 'Bolsa de resucitación adulto (Ambú)', 'Oxigenoterapia', 'Equipo', 'Bolso Azul Vía Aérea Ferno', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(290376, 'Bolsa de resucitación pediátrico (Ambú)', 'Oxigenoterapia', 'Equipo', 'Bolso Azul Vía Aérea Ferno', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(184720, 'Máscara laríngea adulto', 'Oxigenoterapia', 'Equipo', 'Bolso Azul Vía Aérea Ferno', 'NoDefinido', 2, 0, 'Disponible', '{}'::jsonb, '', ''),
(184721, 'Máscara laríngea pediátrica', 'Oxigenoterapia', 'Equipo', 'Bolso Azul Vía Aérea Ferno', 'NoDefinido', 2, 0, 'Disponible', '{}'::jsonb, '', ''),
(176589, 'Guantes de látex talla M', 'EPP y Ropa descartable Ambulancia', 'Descartable', '7 compartimento Mueble', 'NoDefinido', 2, 0, 'Disponible', '{}'::jsonb, '', ''),
(186589, 'Guantes de látex talla L', 'EPP y Ropa descartable Ambulancia', 'Descartable', '7 compartimento Mueble', 'NoDefinido', 2, 0, 'Disponible', '{}'::jsonb, '', ''),
(140988, 'Nebulizador de mano', 'Oxigenoterapia', 'Equipo', 'Bolso Azul Vía Aérea Ferno', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(293422, 'Mascarilla de oxígeno con reservorio adulto', 'Oxigenoterapia', 'Descartable', 'Bolso Azul Vía Aérea Ferno', 'NoDefinido', 2, 0, 'Disponible', '{}'::jsonb, '', ''),
(293423, 'Mascarilla de oxígeno con reservorio pediátrico', 'Oxigenoterapia', 'Descartable', 'Bolso Azul Vía Aérea Ferno', 'NoDefinido', 2, 0, 'Disponible', '{}'::jsonb, '', ''),
(290582, 'Termómetro infrarrojo', 'Equipo de Signos Vitales', 'Equipo', 'Bolso Signos Vitales', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(176499, 'Fonendoscopio adulto', 'Equipo de Signos Vitales', 'Equipo', 'Bolso Signos Vitales', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(190552, 'Fonendoscopio pediátrico', 'Equipo de Signos Vitales', 'Equipo', 'Bolso Signos Vitales', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(115699, 'Tensiómetro aneroide adulto', 'Equipo de Signos Vitales', 'Equipo', 'Bolso Signos Vitales', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(115700, 'Tensiómetro aneroide pediátrico', 'Equipo de Signos Vitales', 'Equipo', 'Bolso Signos Vitales', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(184499, 'Collarín cervical rígido adulto', 'Equipo de Inmovilización', 'Equipo', 'Bolso Azul Vía Aérea Ferno', 'NoDefinido', 2, 0, 'Disponible', '{}'::jsonb, '', ''),
(184500, 'Collarín cervical rígido pediátrico', 'Equipo de Inmovilización', 'Equipo', 'Bolso Azul Vía Aérea Ferno', 'NoDefinido', 2, 0, 'Disponible', '{}'::jsonb, '', ''),
(150299, 'Férula de brazo', 'Equipo de Inmovilización', 'Equipo', 'Bolso Azul Vía Aérea Ferno', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(150300, 'Férula de pierna', 'Equipo de Inmovilización', 'Equipo', 'Bolso Azul Vía Aérea Ferno', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(180991, 'Camilla de lona plegable', 'Equipo de Inmovilización', 'Equipo', 'Modulo De Ambulancia', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(150001, 'Tabla espinal rígida', 'Equipo de Inmovilización', 'Equipo', 'Modulo De Ambulancia', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(185778, 'Sistema de sujeción pediátrico', 'Equipo de Inmovilización', 'Equipo', 'Modulo De Ambulancia', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', ''),
(190999, 'Inmovilizador de cabeza', 'Equipo de Inmovilización', 'Equipo', 'Modulo De Ambulancia', 'NoDefinido', 1, 0, 'Disponible', '{}'::jsonb, '', '');
